# Generated by Django 4.2.11 on 2024-04-06 02:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('birthDate', models.DateField()),
                ('address', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('Nurse', 'Nurse'), ('Administrative', 'Administrative'), ('HumanResources', 'HumanResources'), ('InformationSupport', 'InformationSupport'), ('Doctor', 'Doctor')], max_length=100)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.hospital')),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('birthDate', models.DateField()),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=100)),
                ('emergencyContactName', models.CharField(max_length=100)),
                ('emergencyContactPhone', models.CharField(max_length=15)),
                ('gender', models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE')], max_length=100)),
                ('emergencyContactRelationship', models.CharField(choices=[('Sister', 'Sister'), ('Friend', 'Friend'), ('Son', 'Son'), ('Brother', 'Brother'), ('Daughter', 'Daughter'), ('Father', 'Father'), ('Other', 'Other'), ('Mother', 'Mother')], max_length=100)),
                ('medicalInsuranceName', models.CharField(max_length=100)),
                ('medicalInsuranceNumber', models.IntegerField()),
                ('medicalInsuranceStatus', models.BooleanField()),
                ('medicalInsuranceExpirationDate', models.DateField()),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.hospital')),
            ],
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('quantity', models.IntegerField()),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.hospital')),
            ],
        ),
    ]
