# Generated by Django 4.2.11 on 2024-05-01 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='emergencyContactRelationship',
            field=models.CharField(choices=[('Friend', 'Friend'), ('Other', 'Other'), ('Daughter', 'Daughter'), ('Brother', 'Brother'), ('Father', 'Father'), ('Son', 'Son'), ('Sister', 'Sister'), ('Mother', 'Mother')], max_length=100),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('FEMALE', 'FEMALE'), ('MALE', 'MALE')], max_length=100),
        ),
        migrations.AlterField(
            model_name='person',
            name='role',
            field=models.CharField(choices=[('HumanResources', 'HumanResources'), ('Doctor', 'Doctor'), ('InformationSupport', 'InformationSupport'), ('Nurse', 'Nurse'), ('Administrative', 'Administrative')], max_length=100),
        ),
    ]
