# Generated by Django 4.2.11 on 2024-05-04 02:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0004_alter_employee_role_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.CharField(choices=[('InformationSupport', 'InformationSupport'), ('Doctor', 'Doctor'), ('Nurse', 'Nurse'), ('Administrative', 'Administrative'), ('HumanResources', 'HumanResources')], max_length=100),
        ),
        migrations.AlterField(
            model_name='patient',
            name='emergencyContactRelationship',
            field=models.CharField(choices=[('Sister', 'Sister'), ('Friend', 'Friend'), ('Other', 'Other'), ('Mother', 'Mother'), ('Father', 'Father'), ('Daughter', 'Daughter'), ('Son', 'Son'), ('Brother', 'Brother')], max_length=100),
        ),
        migrations.CreateModel(
            name='ProcedureOrder',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('quantity', models.IntegerField()),
                ('requireAssistance', models.BooleanField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.order')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.employee'),
        ),
        migrations.AddField(
            model_name='order',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.patient'),
        ),
        migrations.CreateModel(
            name='MedicineOrder',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.medicine')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.order')),
            ],
        ),
        migrations.CreateModel(
            name='diagnosticHelpOrder',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('quantity', models.IntegerField()),
                ('requireAssistance', models.BooleanField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.order')),
            ],
        ),
    ]
