# Generated by Django 4.2.11 on 2024-05-04 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0005_order_alter_employee_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.CharField(choices=[('InformationSupport', 'InformationSupport'), ('HumanResources', 'HumanResources'), ('Administrative', 'Administrative'), ('Nurse', 'Nurse'), ('Doctor', 'Doctor')], max_length=100),
        ),
        migrations.AlterField(
            model_name='patient',
            name='emergencyContactRelationship',
            field=models.CharField(choices=[('Mother', 'Mother'), ('Sister', 'Sister'), ('Daughter', 'Daughter'), ('Other', 'Other'), ('Friend', 'Friend'), ('Son', 'Son'), ('Father', 'Father'), ('Brother', 'Brother')], max_length=100),
        ),
    ]
