# Generated by Django 4.2.11 on 2024-05-04 03:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0006_alter_employee_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnostichelporder',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnosticHelpOrder', to='hospital.order'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.CharField(choices=[('HumanResources', 'HumanResources'), ('Nurse', 'Nurse'), ('InformationSupport', 'InformationSupport'), ('Doctor', 'Doctor'), ('Administrative', 'Administrative')], max_length=100),
        ),
        migrations.AlterField(
            model_name='medicineorder',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicineOrder', to='hospital.order'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='emergencyContactRelationship',
            field=models.CharField(choices=[('Friend', 'Friend'), ('Father', 'Father'), ('Son', 'Son'), ('Mother', 'Mother'), ('Brother', 'Brother'), ('Sister', 'Sister'), ('Daughter', 'Daughter'), ('Other', 'Other')], max_length=100),
        ),
        migrations.AlterField(
            model_name='procedureorder',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procedureOrder', to='hospital.order'),
        ),
    ]
